version: 2.1
jobs:
  build:
    working_directory: ~/scala-playground
    docker:
      - image: ubuntu:21.10
    environment:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - run: echo 'export ARTIFACT_BUILD=$CIRCLE_PROJECT_REPONAME-$CIRCLE_BUILD_NUM.zip' >> $BASH_ENV
      - run:
          name: install sbt jdk and scala
          command: |
            apt update && apt install -y curl gnupg
            echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
            curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | apt-key add
            apt update
            apt install -y sbt scala openjdk-11-jdk
            apt clean && apt autoclean
      - checkout
      - run: scalac -version && javac -version
      - run: scalac HelloWorld.scala
      - run: scala HelloWorld


workflows:
  version: 2
  build:
    jobs:
      - build
  daily_workflow:
    triggers:
      - schedule:
          cron: "0 20 * * *"
          filters:
            branches:
              only: /master/
    jobs:
      - build
