version: 2.1
jobs:
  sdkman:
    working_directory: ~/scala-playground
    docker:
      - image: cimg/openjdk:21.0.0
    environment:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - checkout
      - run: sudo apt update && sudo apt install curl
      - run:
          name: Installing SDKMAN!
          command: |
            curl -s "https://get.sdkman.io" | bash
            echo sdkman_auto_answer=true > $HOME/.sdkman/etc/config
            echo sdkman_auto_selfupdate=true >> $HOME/.sdkman/etc/config
            source "$HOME/.sdkman/bin/sdkman-init.sh"
            echo 'export SDKMAN_DIR="$HOME/.sdkman"' >> $BASH_ENV
            echo 'source "$HOME/.sdkman/bin/sdkman-init.sh"' >> $BASH_ENV
      - run: sdk version
      - run: sdk install scala
      - run: sdk install sbt
      - run: scalac -version && javac -version
      - run: scalac HelloWorld.scala
      - run: scala HelloWorld
workflows:
  version: 2
  build:
    jobs:
      - sdkman
  daily_workflow:
    triggers:
      - schedule:
          cron: "0 20 * * *"
          filters:
            branches:
              only: /master/
    jobs:
      - sdkman
